apiVersion: apps/v1
kind: Deployment
metadata:
 name: test-deploy2
 labels:
  app: test-deploy2
spec:
 replicas: 2
 selector:
  matchLabels:
   project: test2
 template:
  metadata:
   labels:
    project: test2 #labels used by services
  spec:
   containers:
   - name: test-web
     image: httpd
     ports:
     - containerPort: 80
   - name: tomcat
     image: tomcat
     ports:
     - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: test-service-2
 labels:
  env: prod
spec:
 selector:
  project: test2 #select PODS with labels
 ports:
  - name: app-listener
    protocol: TCP
    port: 80 #port on LoadBalancer
    targetPort: 80 #port on POD
  - name: app2-listener
    protocol: TCP
    port: 8000 #port on LoadBalancer
    targetPort: 8080 #port on POD
 type: LoadBalancer
