apiVersion: apps/v1
kind: Deployment
metadata:
 name: test-deploy
 labels:
  app: test-deploy
spec:
 replicas: 2
 selector:
  matchLabels:
   project: test
 template:
  metadata:
   labels:
    project: test #labels used by services
  spec:
   containers:
   - name: test-web
     image: httpd
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: test-service-1
 labels:
  env: prod
spec:
 selector:
  project: test #select PODS with labels
 ports:
  - name: app-listener
    protocol: TCP
    port: 80 #port on LoadBalancer
    targetPort: 80 #port on POD
 type: LoadBalancer
